services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception_network
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure
      

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - ./mariadb_vm:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - ./wordpress_vm:/var/www/html/wordpress
    networks:
      - inception_network
    depends_on: 
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    restart: on-failure

networks:
  inception_network:
    driver: bridge

