networks:
  inception_network:
    driver: bridge
  
volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/inazaria/data/mysql
      o: bind

  wordpress:
    driver_opts:
      type: none
      device: /home/inazaria/data/wordpress
      o: bind

services:
  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: on-failure
      

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:inception
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:inception
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception_network
    depends_on: 
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    restart: on-failure
